services:
  app:
    build:
      context: .
    ports:
      - 80:80
    # Compose Watch configuration for automatic rebuilds on code changes
    # This watches for changes in the entire project and triggers a rebuild
    develop:
      watch:
        - action: rebuild
          path: .
